services:
  mongo7-workshop:
    image: mongo:7.0
    volumes:
      - ./data:/data/db
      - ./scripts:/scripts
      - ./indexes:/indexes
      - ./copyMongoAtlasUnix.sh:/copyMongoAtlasUnix.sh
    ports:
      - "27017:27017"